import { test } from 'node:test';
import assert from 'node:assert/strict';

import { buildEnvFileContent } from './setup.mjs';

test('writes every provided key=value pair, quoted', () => {
  const content = buildEnvFileContent({
    DATABASE_URL: 'postgresql://devos:devos-local-only@localhost:5432/devos?schema=public',
    REDIS_URL: 'redis://localhost:6379',
    KEYCLOAK_CLIENT_ID: 'devos',
  });

  assert.match(content, /^DATABASE_URL="postgresql:\/\/devos:devos-local-only@localhost:5432\/devos\?schema=public"$/m);
  assert.match(content, /^REDIS_URL="redis:\/\/localhost:6379"$/m);
  assert.match(content, /^KEYCLOAK_CLIENT_ID="devos"$/m);
});

test('omits keys with empty, undefined or null values, without leaving blank value lines', () => {
  const content = buildEnvFileContent({
    DATABASE_URL: 'postgresql://devos:devos-local-only@localhost:5432/devos?schema=public',
    GITHUB_TOKEN: '',
    GRAFANA_API_KEY: undefined,
    HARBOR_PASSWORD: null,
  });

  assert.match(content, /^DATABASE_URL=/m);
  assert.doesNotMatch(content, /GITHUB_TOKEN/);
  assert.doesNotMatch(content, /GRAFANA_API_KEY/);
  assert.doesNotMatch(content, /HARBOR_PASSWORD/);
});

test('escapes special characters (#, spaces, quotes, backslashes) so the value round-trips', () => {
  const content = buildEnvFileContent({
    WOODPECKER_TOKEN: 'value with spaces and # a hash',
    HARBOR_PASSWORD: 'p"a\\ss#w0rd',
  });

  const lines = Object.fromEntries(
    content
      .split('\n')
      .filter((line) => line.includes('='))
      .map((line) => {
        const eq = line.indexOf('=');
        return [line.slice(0, eq), line.slice(eq + 1)];
      }),
  );

  assert.equal(lines.WOODPECKER_TOKEN, '"value with spaces and # a hash"');
  assert.equal(lines.HARBOR_PASSWORD, '"p\\"a\\\\ss#w0rd"');
});

test('produces an empty-integration file that still has header comments and trailing newline', () => {
  const content = buildEnvFileContent({});
  assert.match(content, /^# Generated by scripts\/setup\.mjs/);
  assert.ok(content.endsWith('\n'));
});
